### ISSUE TITLE
请问如何获得播放的清晰度,还有切换视频

### ISSUE THREAD

**Issue by FjcD** [alilmq/h5demo#1]
播放中,如何获得视频当前使用的清晰度?
prismplayer初始化后,如果是使用source的方式来播放的,如何切换?
刚开始写前端,求教

**Comment by alilmq** [comment]
1. 现在没有获取当前播放地址的方法， 可以通过获取video的src的属性值的方法得到
var src = $(player.el()).find('video').attr('src')
2. 切换source可以通过loadByUrl的方法，切换播放地址

**Comment by FjcD** [comment]
好的,我试一下,谢谢!
