### ISSUE TITLE
2.2以后更换了vid+playauth的播放地址

### ISSUE THREAD

**Issue by kaxijun** [alilmq/h5demo#11]
2.2以后的版本web播放器通过vid+playauth的方式播放
视频文件正常,音频文件会出现404,,,是2.2以后不支持播放音频了吗

**Comment by alilmq** [comment]
现在vid+playauth的方式，只能获取到视频文件， h5支持mp3播放放的， 不过只支持音频的source方式播放

**Comment by kaxijun** [comment]
那2.1版本中,vid+playauth方式的接口会继续保留吗

**Comment by alilmq** [comment]
现在还保留的，但不保证以后不会修改逻辑，后面的版本会提供参数用于指定是获取视频还是mp3音频
