### ISSUE TITLE
关于Android端无法自动播放问题

### ISSUE THREAD

**Issue by Dotcom1989** [alilmq/h5demo#14]
一，无法自动播放
测试环境：
1.chrome浏览器
2.Webkit内核APP

二，点击全屏按钮无效
测试环境：Webkit内核APP iframe框架下
（allowfullscreen="true" webkitallowfullscreen="true" mozallowfullscreen="true"  已添加）
点击全屏按钮报错提示：Uncaught TypeError: Cannot read property 'getIsFullScreen' of undefined at https://g.alicdn.com/de/prismplayer/2.4.0/aliplayer-min.js:4

**Comment by Dotcom1989** [comment]
在之前2.2版本2个问题都是OK的

**Comment by alilmq** [comment]
1. 不能自动播放，一般是浏览器的限制，需要用户的交互
2. 现在需要调用fullscreenService.getIsFullScreen方法
