### ISSUE TITLE
移动端视频自动播放失效了么？

### ISSUE THREAD

**Issue by weizhengda** [alilmq/h5demo#16]
如题，好像官方的在线demo视频自动播放也是失效的（iOS可以，android好像是无效的），请问可以解决吗？

**Comment by alilmq** [comment]
H5Video自动播放视频只有两个办法，通过设置autoplay属性或者调用play()方法，但是现实是在移动端中视频自动播放一直是被禁止的，目前通用的办法是通过用户手动触发播放（例如 监听用户的点击事件并调用 play()方法，但是不排出一些特性的浏览器和webview允许自动播放器，特别是在Android上，现在没有好的办法，只能引导用户操作

**Comment by weizhengda** [comment]
好的，谢谢，另外一个问题想问下，直播demo里面的弹幕功能需要后端来配合实现么？

**Comment by alilmq** [comment]
需要后端配合的， 前端可以通过websocket与后端建立链接，接收弹幕

**Comment by YuFengDing** [comment]
你好，请问一下现在这个demo源码是不对外公布了么 - -

**Comment by alilmq** [comment]
新的代码为：https://github.com/aliyunvideo/AliyunPlayer_Web/tree/master/h5VodDemo
