### ISSUE TITLE
关于播放器的配置

### ISSUE THREAD

**Issue by felanny** [alilmq/h5demo#17]
能不能提供下完整详细的配置文档，比如如果我需要定制一下皮肤，找不到相关的文档啊...
现在播放器有个cover封面，这个封面图没有铺满播放器，左右有黑边，该如何设置

**Comment by felanny** [comment]
改了css源码解决了，但还是希望文档能给详细一点，阿里云那边也是

**Comment by alilmq** [comment]
https://help.aliyun.com/document_detail/62947.html?spm=5176.doc51991.2.19.r1IqqR 这里有个皮肤定义文档， 可以修改CSS的

**Comment by felanny** [comment]
建议这个文档入口放明显点吧
解决了  关闭咯
