### ISSUE TITLE
aliplayer2.0版本的bug·

### ISSUE THREAD

**Issue by lyllionel** [alilmq/h5demo#4]
在使用aliplayer2.0全屏无法真正全屏，我的华为荣耀6底部部分不能顶慢，同时横竖屏切换之后，视频不能正常播放

**Comment by alilmq** [comment]
是在微信里面播放吗？ 铺满这个屏幕可以参考 https://github.com/alilmq/h5livedemo 这个项目，  另外可以通过设置object-fit，和object-positon的值，自定义视频的显示， 请参考 https://player.alicdn.com/aliplayer/docs/blogs/how-to-handle-h5-same-layer.html

**Comment by lyllionel** [comment]
是的，就是微信里面播放。你这个demo我看过了，你这个直接就没办法横竖屏切换，而是变成了铺满，看不到bug存在，但是我这个直播不是手机拍摄的直播，全屏就不好看了

**Comment by alilmq** [comment]
x5_orientation:landscape|portrain 这个属性设置为这个有用吗？微信就提供了这个属性可设置
