### ISSUE TITLE
新版本播放中不会自动隐藏控件

### ISSUE THREAD

**Issue by Dotcom1989** [alilmq/h5demo#6]
主要是移动端
在进入播放后没隐藏控件 遮挡视频内容 影响用户体验

希望可以得到解决 谢谢

**Comment by alilmq** [comment]
确认一下是不是controlBarVisibility属性值设置为always
默认为’click’， 可选的值为：’click’、’hover’、’always’

**Comment by Dotcom1989** [comment]
大赞！已解决了 完美
