### ISSUE TITLE
微信中，先点击全屏，再点击播放按钮，视频黑屏不显示，只能听见声音

### ISSUE THREAD

**Issue by zjzmyh** [alilmq/h5demo#8]
微信中，先点击全屏，再点击播放按钮，视频黑屏不显示，只能听见声音，demo就是这样

**Comment by alilmq** [comment]
微信中如果先全屏，再点击播放，微信还会再弹出一层全屏播放视频，视频被覆盖住了，现在解决方案只能提示用户点播放，然后再全屏显示
